language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

sudo: false

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=clover.xml
  - vendor/squizlabs/php_codesniffer/scripts/phpcs -p --standard=PSR2 ./src
