language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - bin/phpunit --coverage-text --coverage-clover=clover.xml
  - bin/phpcs -p --standard=PSR2 ./src
